#!/usr/bin/env ruby
# frozen_string_literal: true

STDOUT.sync = true

require "superbot"
require "superbot/cloud"
require_relative "../lib/superbot/teleport"

cli = ::Superbot::CLI::TeleportCommand.run
